#%RAML 1.0 DataType
type: object
properties:
  customerId:
    type: number
    required: false
    example: 23457
  customerName:
    type: string
    required: false
    example: "john"
  phoneNum:
    type: number
    required: false
    example: 7890765432
  address:
    type: string
    required: false
    example: kphb
          
      

          
      

    
      