#%RAML 1.0 DataType
type: object
properties:
  productId:
    type: number
    required: false
    example: 345
  productName:
    type: string
    required: false
    example: "AC"
  price:
    type: string
    required: false
    example: "20000"
  productBrand:
    type: string
    required: false
    example: "Ogeneral-AC"
  qty:
    type: number
    required: false
    example: 100
          
          
          
          
      