#%RAML 1.0 DataType
type: object
properties:
  transactionId:
    type: number
    required: false
    example: 34567
  transactionDate:
    type: string
    required: false
    example: "10-11-2022"
  productBrand:
    type: string
    required: false
    example: "sony"
  productId:
    type: number
    required: false
    example: 4567
  productName:
    type: string
    required: false
    example: "mobile"
  paymentMode:
    type: string
    required: false
    example: "onlinetransaction"
          
      

      
      

          
      